insert into USA_STATES_MASTER  values (STATES_SEQ.NEXTVAL,'AL','Alabama');
insert into USA_STATES_MASTER  values (STATES_SEQ.NEXTVAL, 'AK','Alaska');
insert into USA_STATES_MASTER  values (STATES_SEQ.NEXTVAL, 'AS','American Samoa');
insert into USA_STATES_MASTER  values (STATES_SEQ.NEXTVAL, 'AZ','Arizona');
insert into USA_STATES_MASTER  values (STATES_SEQ.NEXTVAL, 'AR','Arkansas');
insert into USA_STATES_MASTER  values (STATES_SEQ.NEXTVAL, 'CA','California');
insert into USA_STATES_MASTER  values (STATES_SEQ.NEXTVAL, 'CO','Colorado');
insert into USA_STATES_MASTER  values (STATES_SEQ.NEXTVAL, 'CT','Connecticut');
insert into USA_STATES_MASTER  values (STATES_SEQ.NEXTVAL, 'DE','Delaware');
insert into USA_STATES_MASTER  values (STATES_SEQ.NEXTVAL, 'DC','District of Columbia');
insert into USA_STATES_MASTER  values (STATES_SEQ.NEXTVAL, 'FM','Federated States of Micronesia');
insert into USA_STATES_MASTER  values (STATES_SEQ.NEXTVAL, 'FL','Florida');
insert into USA_STATES_MASTER  values (STATES_SEQ.NEXTVAL, 'GA','Georgia');
insert into USA_STATES_MASTER  values (STATES_SEQ.NEXTVAL, 'GU','Guam');
insert into USA_STATES_MASTER  values (STATES_SEQ.NEXTVAL, 'HI','Hawaii');
insert into USA_STATES_MASTER  values (STATES_SEQ.NEXTVAL, 'ID','Idaho');
insert into USA_STATES_MASTER  values (STATES_SEQ.NEXTVAL, 'IL','Illinois');
insert into USA_STATES_MASTER  values (STATES_SEQ.NEXTVAL, 'IN','Indiana');
insert into USA_STATES_MASTER  values (STATES_SEQ.NEXTVAL, 'IA','Iowa');
insert into USA_STATES_MASTER  values (STATES_SEQ.NEXTVAL, 'KS','Kansas');
insert into USA_STATES_MASTER  values (STATES_SEQ.NEXTVAL, 'KY','Kentucky');
insert into USA_STATES_MASTER  values (STATES_SEQ.NEXTVAL, 'LA','Louisiana');
insert into USA_STATES_MASTER  values (STATES_SEQ.NEXTVAL, 'ME','Maine');
insert into USA_STATES_MASTER  values (STATES_SEQ.NEXTVAL, 'MH','Marshall Islands');
insert into USA_STATES_MASTER  values (STATES_SEQ.NEXTVAL, 'MD','Maryland');
insert into USA_STATES_MASTER  values (STATES_SEQ.NEXTVAL, 'MA','Massachusetts');
insert into USA_STATES_MASTER  values (STATES_SEQ.NEXTVAL, 'MI','Michigan');
insert into USA_STATES_MASTER  values (STATES_SEQ.NEXTVAL, 'MN','Minnesota');
insert into USA_STATES_MASTER  values (STATES_SEQ.NEXTVAL, 'MS','Mississippi');
insert into USA_STATES_MASTER  values (STATES_SEQ.NEXTVAL, 'MO','Missouri');
insert into USA_STATES_MASTER  values (STATES_SEQ.NEXTVAL, 'MT','Montana');
insert into USA_STATES_MASTER  values (STATES_SEQ.NEXTVAL, 'NE','Nebraska');
insert into USA_STATES_MASTER  values (STATES_SEQ.NEXTVAL, 'NV','Nevada');
insert into USA_STATES_MASTER  values (STATES_SEQ.NEXTVAL, 'NH','New Hampshire');
insert into USA_STATES_MASTER  values (STATES_SEQ.NEXTVAL, 'NJ','New Jersey');
insert into USA_STATES_MASTER  values (STATES_SEQ.NEXTVAL, 'NM','New Mexico');
insert into USA_STATES_MASTER  values (STATES_SEQ.NEXTVAL, 'NY','New York');
insert into USA_STATES_MASTER  values (STATES_SEQ.NEXTVAL, 'NC','North Carolina');
insert into USA_STATES_MASTER  values (STATES_SEQ.NEXTVAL, 'ND','North Dakota');
insert into USA_STATES_MASTER  values (STATES_SEQ.NEXTVAL, 'MP','Northern Mariana Islands');
insert into USA_STATES_MASTER  values (STATES_SEQ.NEXTVAL, 'OH','Ohio');
insert into USA_STATES_MASTER  values (STATES_SEQ.NEXTVAL, 'OK','Oklahoma');
insert into USA_STATES_MASTER  values (STATES_SEQ.NEXTVAL, 'OR','Oregon');
insert into USA_STATES_MASTER  values (STATES_SEQ.NEXTVAL, 'PW','Palau');
insert into USA_STATES_MASTER  values (STATES_SEQ.NEXTVAL, 'PA','Pennsylvania');
insert into USA_STATES_MASTER  values (STATES_SEQ.NEXTVAL, 'PR','Puerto Rico');
insert into USA_STATES_MASTER  values (STATES_SEQ.NEXTVAL, 'RI','Rhode Island');
insert into USA_STATES_MASTER  values (STATES_SEQ.NEXTVAL, 'SC','South Carolina');
insert into USA_STATES_MASTER  values (STATES_SEQ.NEXTVAL, 'SD','South Dakota');
insert into USA_STATES_MASTER  values (STATES_SEQ.NEXTVAL, 'TN','Tennessee');
insert into USA_STATES_MASTER  values (STATES_SEQ.NEXTVAL, 'TX','Texas');
insert into USA_STATES_MASTER  values (STATES_SEQ.NEXTVAL, 'UT','Utah');
insert into USA_STATES_MASTER  values (STATES_SEQ.NEXTVAL, 'VT','Vermont');
insert into USA_STATES_MASTER  values (STATES_SEQ.NEXTVAL, 'VI','Virgin Islands');
insert into USA_STATES_MASTER  values (STATES_SEQ.NEXTVAL, 'VA','Virginia');
insert into USA_STATES_MASTER  values (STATES_SEQ.NEXTVAL, 'WA','Washington');
insert into USA_STATES_MASTER  values (STATES_SEQ.NEXTVAL, 'WV','West Virginia');
insert into USA_STATES_MASTER  values (STATES_SEQ.NEXTVAL, 'WI','Wisconsin');
insert into USA_STATES_MASTER  values (STATES_SEQ.NEXTVAL, 'WY','Wyoming');
commit;